### ISSUE TITLE
TypeError: %d format: a number is required, not NoneType

### ISSUE THREAD

**Issue by John1231983** [tiepvupsu/zalo_landmark#1]
I am using pytorch 0.4.1 and cuda 9.1, python 3.6. I got an error when run `python train.py`

https://github.com/tiepvupsu/zalo_landmark/blob/70d56669fc2a909f2ddc77f757a35b96434df81d/src/zalo_utils.py#L111

How should I fix it? Thanks so much

```
python train.py 
Loading data
Total files in the original dataset: 88246
Total files with > 0 byes: 88220
Total files with zero bytes 26
Split data
Number of training imgs: 79398
Number of validation imgs: 8822
DataLoader ....
/home/john/anaconda3/lib/python3.6/site-packages/torchvision/transforms/transforms.py:563: UserWarning: The use of the transforms.RandomSizedCrop transform is deprecated, please use transforms.RandomResizedCrop instead.
  "please use transforms.RandomResizedCrop instead.")
/home/john/anaconda3/lib/python3.6/site-packages/torchvision/transforms/transforms.py:188: UserWarning: The use of the transforms.Scale transform is deprecated, please use transforms.Resize instead.
  "please use transforms.Resize instead.")
Load model
Start training ... 
********************************************************
Traceback (most recent call last):
  File "train.py", line 137, in <module>
    model, optimizer = net_frozen(args, model)
  File "/home/john/zalo_landmark/src/zalo_utils.py", line 151, in net_frozen
    model.frozen_until(args.frozen_until)
  File "/home/john/zalo_landmark/src/zalo_utils.py", line 113, in frozen_until
    print('Frozen shared part until %d-th layer, inclusive' % to_layer)
TypeError: %d format: a number is required, not NoneType
```

**Comment by tiepvupsu** [comment]
I fixed the error. Please run it again.

**Comment by 0904-mansi** [comment]
> I fixed the error. Please run it again.

How did you fix this error? I am also getting same please help!
